name: CI/CD Pipeline

on:
  push:
    branches: [ master ]  # or your target branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '21' # or your project version

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Deploy to Azure VM via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_KEY }}
        source: "build/libs/*.jar"
        target: "~/app"

    - name: Restart Java App on Azure VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_KEY }}
        script: |
            pkill -f 'java -jar' || true
            nohup java -jar ~/app/PatientManagement-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            sleep 5
            tail -n 20 app.log
